project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: Hands-on-Exercise
        menu:
          - href: Hands-On_Ex/Hands-On_Ex01/Hands-On_Ex01.html
            text: Hands-On Exercise 1
          - href: Hands-On_Ex/Hands-On_Ex02/Hands-On_Ex02.html
            text: Hands-On Exercise 2
          - href: Hands-On_Ex/Hands-On_Ex03/Hands-On_Ex03.html
            text: Hands-On Exercise 3
          
      - text: In-class Exercise
        menu:
          - href: In-Class_Ex/In-Class_Ex02/In-Class_Ex02.html
            text: In-Class Exercise 2
          - href: In-Class_Ex/In-Class_Ex03/In-Class_Ex03.html
            text: In-Class Exercise 3
          - href: In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html
            text: In-Class Exercise 4
            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual
