project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: Hands-on-Exercise
        menu:
          - href: Hands-On_Ex/Hands-On_Ex01/Hands-On_Ex01.html
            text: Hands-On Exercise 1
          - href: Hands-On_Ex/Hands-On_Ex02/Hands-On_Ex02.html
            text: Hands-On Exercise 2
          - href: Hands-On_Ex/Hands-On_Ex03/Hands-On_Ex03.html
            text: Hands-On Exercise 3
          - href: Hands-On_Ex/Hands-On_Ex03_1/Hands-On_Ex03_1.html
            text: Hands-On Exercise 3.1
          - href: Hands-On_Ex/Hands-On_Ex06/Hands-On_Ex06.html
            text: Hands-On Exercise 6
          - href: Hands-On_Ex/Hands-On_Ex07/Hands-On_Ex07.html
            text: Hands-On Exercise 7
          - href: Hands-On_Ex/Hands-On_Ex07_1/Hands-On_Ex07_1.html
            text: Hands-On Exercise 7.1
          - href: Hands-On_Ex/Hands-On_Ex09/Hands-On_Ex09.html
            text: Hands-On Exercise 9
          
      - text: In-class Exercise
        menu:
          - href: In-Class_Ex/In-Class_Ex02/In-Class_Ex02.html
            text: In-Class Exercise 2
          - href: In-Class_Ex/In-Class_Ex03/In-Class_Ex03.html
            text: In-Class Exercise 3
          - href: In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html
            text: In-Class Exercise 4
          - href: In-Class_Ex/In-Class_Ex05/In-Class_Ex05.html
            text: In-Class Exercise 5
          - href: In-Class_Ex/In-Class_Ex06/In-Class_Ex06.html
            text: In-Class Exercise 6
          - href: In-Class_Ex/In-Class_Ex07/In-Class_Ex07-GLSA.html
            text: In-Class Exercise 7-GLSA
          - href: In-Class_Ex/In-Class_Ex07/In-Class_Ex07-EHSA.html
            text: In-Class Exercise 7-EHSA
          - href: In-Class_Ex/In-Class_Ex08/In-Class_Ex08.html
            text: In-Class Exercise 8
      - text: Take Home Exercise
        menu:
          - href: Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html
            text: Take Home Exercise 1
          - href: Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html
            text: Take Home Exercise 2
            
    right:
      - href: index.html
        text: Home
      - href: about.html
        text: About

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual
